image:
  file: .devcontainer/.gitpod.Dockerfile

tasks:
  - init: "dotnet tool restore && dotnet restore && dotnet build"
    command: "dotnet watch --project src/MagicCollectionHelper/AvaloniaApp/ run"

vscode:
  extensions:
    - ionide.ionide-fsharp
    - editorconfig.editorconfig
    - muhammad-sammy.csharp
    - eamodio.gitlens
    - ybaumes.highlight-trailing-white-spaces
    - gruntfuggly.todo-tree
