image:
  file: .devcontainer/.gitpod.Dockerfile

tasks:
  - init: "./run.fsx build"
    command: "./run.fsx setup-testdata && dotnet watch --project src/MagicCollectionHelper/AvaloniaApp/ run"

vscode:
  extensions:
    - ionide.ionide-fsharp
    - editorconfig.editorconfig
    - muhammad-sammy.csharp
    - eamodio.gitlens
    - ybaumes.highlight-trailing-white-spaces
    - gruntfuggly.todo-tree
