image:
  file: .devcontainer/.gitpod.Dockerfile

tasks:
  - init: "dotnet tool restore && dotnet restore && dotnet build"
    command: "dotnet watch --project src/MagicCollectionHelper/AvaloniaApp/ run"

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==
    - ionide.ionide-fsharp@5.3.2:ktwOdXq2H8VHS6SX8scVIw==
