image:
  file: .devcontainer/.gitpod.Dockerfile

tasks:
  - init: "./run.fsx setup-testdata && ./run.fsx build"

vscode:
  extensions:
    - ionide.ionide-fsharp
    - editorconfig.editorconfig
    - muhammad-sammy.csharp
    - eamodio.gitlens
    - ybaumes.highlight-trailing-white-spaces
    - gruntfuggly.todo-tree
