image:
  file: .devcontainer/.gitpod.Dockerfile

tasks:
  - init: "dotnet run setup-testdata && dotnet run build"

vscode:
  extensions:
    - ionide.ionide-fsharp
    - editorconfig.editorconfig
    - muhammad-sammy.csharp
    - eamodio.gitlens
    - ybaumes.highlight-trailing-white-spaces
    - gruntfuggly.todo-tree
