//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec MagicCollectionHelper.AvaloniaApp

module SearchLenses =
    open MagicCollectionHelper.AvaloniaApp.DomainTypes
    let text =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: Search) -> x.text),
            (fun (x: Search) (value: string) -> { x with text = value })
        )

    let old =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: Search) -> x.old),
            (fun (x: Search) (value: bool option) -> { x with old = value })
        )
namespace rec MagicCollectionHelper.AvaloniaApp

module Search =
    open MagicCollectionHelper.AvaloniaApp.DomainTypes
    let text (x: Search) = x.text
    let old (x: Search) = x.old
    let create (text: string) (old: bool option) : Search = { text = text; old = old }
    let map (maptext: string -> string) (mapold: bool option -> bool option) (record': Search) =
        { record' with
              text = maptext record'.text
              old = mapold record'.old }
