//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec MagicCollectionHelper.AvaloniaApp.Main.Generated

module CommonStateLenses =
    open MagicCollectionHelper.AvaloniaApp.Main
    let analyseText =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: CommonState) -> x.analyseText),
            (fun (x: CommonState) (value: string) -> { x with analyseText = value })
        )

    let dsEntries =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: CommonState) -> x.dsEntries),
            (fun (x: CommonState) (value: MagicCollectionHelper.Core.Types.DeckStatsCardEntry list) ->
                { x with dsEntries = value })
        )

    let entries =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: CommonState) -> x.entries),
            (fun (x: CommonState) (value: MagicCollectionHelper.Core.Types.CardEntry list) ->
                { x with entries = value })
        )

    let infoMap =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: CommonState) -> x.infoMap),
            (fun (x: CommonState) (value: MagicCollectionHelper.Core.Types.CardInfoMap) -> { x with infoMap = value })
        )

    let prefs =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: CommonState) -> x.prefs),
            (fun (x: CommonState) (value: MagicCollectionHelper.Core.Types.Prefs) -> { x with prefs = value })
        )

    let setData =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: CommonState) -> x.setData),
            (fun (x: CommonState) (value: MagicCollectionHelper.Core.Types.SetDataMap) -> { x with setData = value })
        )

    let viewMode =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: CommonState) -> x.viewMode),
            (fun (x: CommonState) (value: ViewMode) -> { x with viewMode = value })
        )
namespace rec MagicCollectionHelper.AvaloniaApp.Main.Generated

module StateLenses =
    open MagicCollectionHelper.AvaloniaApp.Main
    let common =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.common),
            (fun (x: State) (value: CommonState) -> { x with common = value })
        )

    let collection =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.collection),
            (fun (x: State) (value: MagicCollectionHelper.AvaloniaApp.Components.Collection.State) ->
                { x with collection = value })
        )

    let inventory =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.inventory),
            (fun (x: State) (value: MagicCollectionHelper.AvaloniaApp.Components.Inventory.State) ->
                { x with inventory = value })
        )
