//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec MagicCollectionHelper.AvaloniaApp.Components.Main

module StateLenses =
    open MagicCollectionHelper.AvaloniaApp.Components.Main
    let analyseText =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.analyseText),
            (fun (x: State) (value: string) -> { x with analyseText = value })
        )

    let cards =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.cards),
            (fun (x: State) (value: MagicCollectionHelper.Core.Types.CardEntry list) -> { x with cards = value })
        )

    let prefs =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.prefs),
            (fun (x: State) (value: MagicCollectionHelper.Core.Types.Prefs) -> { x with prefs = value })
        )

    let setData =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.setData),
            (fun (x: State) (value: MagicCollectionHelper.Core.Types.SetDataMap) -> { x with setData = value })
        )

    let viewMode =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.viewMode),
            (fun (x: State) (value: ViewMode) -> { x with viewMode = value })
        )
