["components-collection"]
namespace = "MagicCollectionHelper.AvaloniaApp.Components.Collection.Generated"

["components-inventory"]
namespace = "MagicCollectionHelper.AvaloniaApp.Components.Inventory.Generated"

["components-main"]
namespace = "MagicCollectionHelper.AvaloniaApp.Components.Main.Generated"
