["components-collection"]
namespace = "MagicCollectionHelper.AvaloniaApp.Components.Collection.Generated"

["components-inventory"]
namespace = "MagicCollectionHelper.AvaloniaApp.Components.Inventory.Generated"

["main"]
namespace = "MagicCollectionHelper.AvaloniaApp.Main.Generated"

["root"]
namespace = "MagicCollectionHelper.AvaloniaApp.Generated"
