//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec MagicCollectionHelper.AvaloniaApp.Generated

module LoadingState =
    open MagicCollectionHelper.AvaloniaApp
    let toString (x: LoadingState) =
        match x with
        | Prepare -> "Prepare"
        | Download -> "Download"
        | Import -> "Import"
        | Ready -> "Ready"

    let fromString (x: string) =
        match x with
        | "Prepare" -> Some Prepare
        | "Download" -> Some Download
        | "Import" -> Some Import
        | "Ready" -> Some Ready
        | _ -> None

    let toTag (x: LoadingState) =
        match x with
        | Prepare -> 0
        | Download -> 1
        | Import -> 2
        | Ready -> 3

    let isPrepare (x: LoadingState) =
        match x with
        | Prepare -> true
        | _ -> false

    let isDownload (x: LoadingState) =
        match x with
        | Download -> true
        | _ -> false

    let isImport (x: LoadingState) =
        match x with
        | Import -> true
        | _ -> false

    let isReady (x: LoadingState) =
        match x with
        | Ready -> true
        | _ -> false
