FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-focal

# We have to create this folder by ourselfes, otherwise the permissions are wrong
RUN sudo -u vscode mkdir -p /home/vscode/.local/share
