//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec MagicCollectionHelper.AvaloniaApp.Components.Inventory

module StateLenses =
    open MagicCollectionHelper.AvaloniaApp.Components.Inventory
    let inventory =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.inventory),
            (fun (x: State) (value: LocationCardMap) -> { x with inventory = value })
        )

    let loadInProgress =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.loadInProgress),
            (fun (x: State) (value: bool) -> { x with loadInProgress = value })
        )

    let locations =
        MagicCollectionHelper.Core.Types.Lens(
            (fun (x: State) -> x.locations),
            (fun (x: State) (value: MagicCollectionHelper.Core.Types.CustomLocation list) ->
                { x with locations = value })
        )
