//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------


namespace rec MagicCollectionHelper.Core

module Rarity =
    open MagicCollectionHelper.Core.CardPartTypes

    let toString (x: Rarity) =
        match x with
        | Common -> "Common"
        | Uncommon -> "Uncommon"
        | Rare -> "Rare"
        | Mythic -> "Mythic"
        | Special -> "Special"
        | Bonus -> "Bonus"

    let fromString (x: string) =
        match x with
        | "Common" -> Some Common
        | "Uncommon" -> Some Uncommon
        | "Rare" -> Some Rare
        | "Mythic" -> Some Mythic
        | "Special" -> Some Special
        | "Bonus" -> Some Bonus
        | _ -> None

    let toTag (x: Rarity) =
        match x with
        | Common -> 0
        | Uncommon -> 1
        | Rare -> 2
        | Mythic -> 3
        | Special -> 4
        | Bonus -> 5

    let isCommon (x: Rarity) =
        match x with
        | Common -> true
        | _ -> false

    let isUncommon (x: Rarity) =
        match x with
        | Uncommon -> true
        | _ -> false

    let isRare (x: Rarity) =
        match x with
        | Rare -> true
        | _ -> false

    let isMythic (x: Rarity) =
        match x with
        | Mythic -> true
        | _ -> false

    let isSpecial (x: Rarity) =
        match x with
        | Special -> true
        | _ -> false

    let isBonus (x: Rarity) =
        match x with
        | Bonus -> true
        | _ -> false

